name: Start index.js
on: push
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: node file
        run: node index
  getFiles:
    needs: node
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3